### 환경 변수 설정
@host = http://localhost:8080
@accountId = 395ee0b6-2c8f-44b8-adab-ba0af6410c14

### app 서버 헬스체크
GET {{host}}/v1/_healthz
Content-Type: application/json

### 새 계좌 생성
POST {{host}}/v1/account.create
Content-Type: application/json

{
  "user_name": "test_user_1",
  "initial_balance": 10000
}


### 전체 계좌 목록 조회
GET {{host}}/v1/account.list

### 특정 계좌 조회
GET {{host}}/v1/account.info?account_id={{accountId}}


### 입금
POST {{host}}/v1/account.deposit
Content-Type: application/json

{
  "account_id": "395ee0b6-2c8f-44b8-adab-ba0af6410c14",
  "amount": 5000
}

### 출금
POST {{host}}/v1/account.withdraw
Content-Type: application/json

{
  "account_id": "395ee0b6-2c8f-44b8-adab-ba0af6410c14",
  "amount": 2000
}